name: sweeper CI

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sweeper worker
        env:
          SKYSWEEPER_API_KEY: ${{ secrets.SKYSWEEPER_API_KEY }}
        run: |
          curl -v -H "Authorization: Bearer ${SKYSWEEPER_API_KEY}" -X DELETE --connect-timeout 0 --max-time 0 https://worker.skysweeper.p8.lu/posts
